// ─────────────────────────────────────────────────────────────────────────────
// LoginPage.tsx — sign-in for both desk and clients.
//
// Simple centered treatment (§4.1 / login/Simple Login.html):
//   Lodgr. wordmark · tagline · rule · fields · full-width button · rule ·
//   inline alt-mode switch · footer.
//
// Password ⇄ Magic link is an INLINE SWITCH, not tabs. Default = Password.
// Magic mode shows helper text; submit currently shows a friendly error since
// self-serve magic requests are not yet in the backend (desk generates them).
//
// Errors:
//   • 401              — bad email/password, shown inline.
//   • 429 w/ Retry-After — lockout, show countdown.
//   • 429 w/o header   — permanent lockout, show static message.
//   • Anything else    — show the error.error string from the body.
// ─────────────────────────────────────────────────────────────────────────────

import { useEffect, useMemo, useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import type { AxiosError } from 'axios';
import { useAuth } from '../auth/AuthContext';
import { useTheme } from '../theme/ThemeContext';
import type { ApiError } from '../api/types';
import '../styles/login.css';

type Mode = 'password' | 'magic';

function fmtCountdown(sec: number): string {
  const m = Math.floor(sec / 60);
  const s = sec % 60;
  return `${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')}`;
}

export function LoginPage() {
  const { token, login } = useAuth();
  const { theme, toggle } = useTheme();
  const nav = useNavigate();
  const loc = useLocation();

  const from = (loc.state as { from?: { pathname?: string } } | null)?.from?.pathname ?? '/tickets';

  useEffect(() => {
    if (token) nav(from, { replace: true });
  }, [token, from, nav]);

  const [mode, setMode] = useState<Mode>('password');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<{ title: string; body: string } | null>(null);
  const [lockoutUntil, setLockoutUntil] = useState<number | null>(null);

  const [nowMs, setNowMs] = useState(() => Date.now());
  useEffect(() => {
    if (!lockoutUntil) return;
    const i = setInterval(() => setNowMs(Date.now()), 1000);
    return () => clearInterval(i);
  }, [lockoutUntil]);
  const lockoutSec = useMemo(() => {
    if (!lockoutUntil) return 0;
    return Math.max(0, Math.ceil((lockoutUntil - nowMs) / 1000));
  }, [lockoutUntil, nowMs]);
  const locked = lockoutSec > 0;

  function switchMode(next: Mode) {
    setMode(next);
    setError(null);
  }

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (submitting || locked) return;
    setError(null);

    if (mode === 'magic') {
      setError({
        title: 'Ask the desk for a link',
        body: 'Magic links are generated by your desk agent and sent directly to you. Contact them and ask for a one-time sign-in link.',
      });
      return;
    }

    setSubmitting(true);
    try {
      await login(email, password);
    } catch (err) {
      const ax = err as AxiosError<ApiError>;
      const status = ax.response?.status;

      if (status === 429) {
        const ra = ax.response?.headers?.['retry-after'];
        const secs = typeof ra === 'string' ? parseInt(ra, 10) : NaN;
        if (Number.isFinite(secs) && secs > 0) {
          setLockoutUntil(Date.now() + secs * 1000);
          setError({
            title: 'Too many attempts',
            body: `Try again in a moment. We'll re-enable the form when the lockout lifts.`,
          });
        } else {
          setError({
            title: 'Account locked',
            body: ax.response?.data?.error ?? 'Account is permanently locked. Contact support to unlock.',
          });
        }
      } else if (status === 401) {
        setError({
          title: "Those credentials didn't work",
          body: 'Check the email and password, or use a magic link.',
        });
      } else {
        setError({
          title: 'Something went wrong',
          body: ax.response?.data?.error ?? ax.message ?? 'Unknown error',
        });
      }
    } finally {
      setSubmitting(false);
    }
  }

  return (
    <div className="lg-login grain">
      {/* Stroked "L" watermark — bottom-right ornament */}
      <div className="lg-login__bg-l" aria-hidden>L</div>

      {/* Theme toggle — top-right corner */}
      <button
        type="button"
        className="lg-login__theme lg-theme-switch"
        aria-label={theme === 'dark' ? 'Switch to light mode' : 'Switch to dark mode'}
        aria-pressed={theme === 'dark'}
        onClick={(e) => toggle({ x: e.clientX, y: e.clientY })}
      >
        <span className="th-seg th-seg--light">LGT</span>
        <span className="slash" aria-hidden>/</span>
        <span className="th-seg th-seg--dark">DRK</span>
      </button>

      <div className="lg-login__card">
        {/* Wordmark */}
        <div className="lg-login__logo lg-enter" style={{ '--i': 0 } as React.CSSProperties}>
          <i>Lodgr</i><span className="dot">.</span>
        </div>

        {/* Tagline */}
        <div className="lg-login__tag lg-enter" style={{ '--i': 1 } as React.CSSProperties}>
          — Self-hosted support desk —
        </div>

        <div className="lg-login__rule lg-enter" style={{ '--i': 2 } as React.CSSProperties} />

        <form onSubmit={handleSubmit} noValidate>
          {/* Re-key on mode change so the enter animation fires on swap (~420ms ease-out) */}
          <div key={mode} className="lg-login__fields lg-enter" style={{ '--i': 3 } as React.CSSProperties}>
            {error && (
              <div className="lg-login__error" role="alert">
                <b>{error.title}</b>
                {error.body}
                {locked && <> · <b>retry in {fmtCountdown(lockoutSec)}</b></>}
              </div>
            )}

            <div className="lg-login__field">
              <label className="lg-input-label" htmlFor="login-email">Email</label>
              <input
                id="login-email"
                className="lg-input"
                type="email"
                autoComplete="email"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                placeholder="you@example.com"
                disabled={locked}
                required
              />
            </div>

            {mode === 'password' ? (
              <div className="lg-login__field">
                <div className="lg-login__pw-label">
                  <label className="lg-input-label" htmlFor="login-password">Password</label>
                  <button type="button" className="lg-login__forgot">Forgot</button>
                </div>
                <input
                  id="login-password"
                  className="lg-input"
                  type="password"
                  autoComplete="current-password"
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  disabled={locked}
                  required
                />
              </div>
            ) : (
              <p className="lg-login__explainer">
                We'll email you a one-time sign-in link. It expires in <b>15 minutes</b> and works once.
              </p>
            )}
          </div>

          <button
            type="submit"
            className="lg-login__send lg-enter"
            style={{ '--i': 4 } as React.CSSProperties}
            disabled={submitting || locked}
          >
            <span>{submitting ? 'Signing in…' : mode === 'magic' ? 'Send the link' : 'Sign in'}</span>
            {!submitting && <span className="arr">→</span>}
          </button>
        </form>

        <div className="lg-login__rule lg-enter" style={{ '--i': 5 } as React.CSSProperties} />

        {/* Inline mode switch */}
        <div className="lg-login__alt lg-enter" style={{ '--i': 6 } as React.CSSProperties}>
          {mode === 'password' ? (
            <>
              Client?{' '}
              <button type="button" onClick={() => switchMode('magic')}>
                <b>Email me a link</b>
              </button>
              {' '}instead.
            </>
          ) : (
            <>
              Prefer a{' '}
              <button type="button" onClick={() => switchMode('password')}>
                <b>password</b>
              </button>
              ?
            </>
          )}
        </div>

        <div className="lg-login__footer lg-enter" style={{ '--i': 7 } as React.CSSProperties}>
          <span>v0.1.0 · self-hosted</span>
          <span>Built in Nairobi</span>
        </div>
      </div>
    </div>
  );
}
